export const SERVICES = [
  {
    id: 'web-design',
    title: 'Web Design',
    description: 'Beautiful, responsive websites tailored to your brand and goals.',
    icon: 'Palette',
  },
  {
    id: 'hosting',
    title: 'Web Hosting',
    description: 'Fast, reliable hosting with 99.9% uptime and free SSL certificates.',
    icon: 'Server',
  },
  {
    id: 'seo',
    title: 'SEO',
    description: 'Search engine optimization to boost your organic rankings and traffic.',
    icon: 'Search',
  },
  {
    id: 'geo',
    title: 'GEO',
    description: 'Generative Engine Optimization to ensure visibility in modern search engines.',
    icon: 'Globe',
  },
  {
    id: 'sem',
    title: 'SEM',
    description: 'Search engine marketing and paid advertising to drive targeted leads.',
    icon: 'Target',
  },
  {
    id: 'audits',
    title: 'Website Audits',
    description: 'Comprehensive audits covering performance, SEO, accessibility and security.',
    icon: 'ClipboardCheck',
  },
  {
    id: 'google-workspace',
    title: 'Google Workspace',
    description: 'Professional email, Drive, Docs and more — set up and managed for you.',
    icon: 'Mail',
  },
  {
    id: 'web-apps',
    title: 'Web Applications',
    description: 'Custom web apps built with modern frameworks to power your business.',
    icon: 'Code',
  },
] as const

export const PACKAGES = [
  {
    id: 'starter',
    name: 'Starter',
    price: 999,
    description: 'Perfect for small businesses getting online',
    features: [
      'Single-page responsive website',
      'Mobile-friendly design',
      'Free hosting & SSL',
      'Basic SEO setup',
      'Contact form',
      'Domain connection',
      '3 rounds of revisions',
      'Email support',
    ],
    highlighted: false,
  },
  {
    id: 'professional',
    name: 'Professional',
    price: 2499,
    description: 'For growing businesses that need more',
    features: [
      'Multi-page website (up to 8 pages)',
      'Custom design with animations',
      'Free hosting & SSL',
      'Advanced SEO optimization',
      'Blog integration',
      'Google Workspace setup',
      'Social media integration',
      'Analytics dashboard',
      'Priority email & chat support',
      '5 rounds of revisions',
    ],
    highlighted: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 4999,
    description: 'Full-scale digital presence',
    features: [
      'Custom React web application',
      'Unlimited pages',
      'Premium hosting & CDN',
      'Full SEO, GEO & SEM setup',
      'E-commerce capabilities',
      'Google Workspace setup & management',
      'Website audit & optimization',
      'Custom integrations & APIs',
      'Dedicated account manager',
      'Unlimited revisions',
    ],
    highlighted: false,
  },
] as const

export const INDUSTRIES = [
  'Restaurant / Food',
  'Retail / E-commerce',
  'Professional Services',
  'Healthcare',
  'Real Estate',
  'Construction',
  'Education',
  'Technology',
  'Beauty / Wellness',
  'Automotive',
  'Non-profit',
  'Other',
] as const

export const FONT_OPTIONS = [
  'Inter',
  'Poppins',
  'Montserrat',
  'Playfair Display',
  'Roboto',
  'Open Sans',
  'Lato',
  'DM Sans',
] as const
